# Deploys MySQL container with PVC + Secrets.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider-db
  template:
    metadata:
      labels:
        app: rider-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rider-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: rider-config
                  key: DB_NAME
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rider-db
spec:
  selector:
    app: rider-db
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
