# Exposes Flask app (NodePort for local access).

apiVersion: v1
kind: Service
metadata:
  name: rider-service
spec:
  type: NodePort
  selector:
    app: rider-service
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001
      protocol: TCP
